config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :friendships, only: [ :index, :destroy ]
  resources :friend_requests, only: [ :index, :new, :create, :destroy ]
  post "/friend_requests/:id", to: "friend_requests#accept"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :primary_friend, class_name: :User, foreign_key: :primary_friend_id
  belongs_to :secondary_friend, class_name: :User, foreign_key: :secondary_friend_id
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: %i[ destroy ]
  before_action :authenticate_user!

  # GET /friendships or /friendships.json
  def index
    @friendships = current_user.friendships
  end

  # DELETE /friendships/1 or /friendships/1.json
  def destroy
    if !@friendship.nil? && (@friendship.primary_friend == current_user or @friendship.secondary_friend == current_user)
      @friendship.destroy!
    
      respond_to do |format|
        format.html { redirect_to friendships_path, status: :see_other, notice: "Friendship was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friendship_params
      params.require(:friendship).permit(:primary_friend_id, :secondary_friend_id)
    end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_with(model: friendship) do |form| %>
  <% if friendship.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
        <% friendship.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :primary_friend_id, style: "display: block" %>
    <%= form.text_field :primary_friend_id %>
  </div>

  <div>
    <%= form.label :secondary_friend_id, style: "display: block" %>
    <%= form.text_field :secondary_friend_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/friendships/_friendship.html.erb
<div id="<%= dom_id friendship %>">

  <% if current_user==friendship.primary_friend %>
    <%= friendship.secondary_friend.email %>
  <% elsif current_user==friendship.secondary_friend %>
    <%= friendship.primary_friend.email %>
  <% end %>

</div>

app/views/friendships/edit.html.erb
<% content_for :title, "Editing friendship" %>

<h1>Editing friendship</h1>

<%= render "form", friendship: @friendship %>

<br>

<div>
  <%= link_to "Show this friendship", @friendship %> |
  <%= link_to "Back to friendships", friendships_path %>
</div>

app/views/friendships/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Friendships" %>

<h1>Friendships</h1>

<div id="friendships">
  <% @friendships.each do |friendship| %>
    <%= render friendship %>
    <%= button_to friendship_path(friendship), method: :delete do %>
      Unfriend
    <% end %>
    <br><br>

  <% end %>
</div>

app/views/friendships/new.html.erb
<% content_for :title, "New friendship" %>

<h1>New friendship</h1>

<%= render "form", friendship: @friendship %>

<br>

<div>
  <%= link_to "Back to friendships", friendships_path %>
</div>

app/views/friendships/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @friendship %>

<div>
  <%= link_to "Edit this friendship", edit_friendship_path(@friendship) %> |
  <%= link_to "Back to friendships", friendships_path %>

  <%= button_to "Destroy this friendship", @friendship, method: :delete %>
</div>