config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :friendships, only: [ :index, :destroy ]
  resources :friend_requests, only: [ :index, :new, :create, :destroy ]
  post "/friend_requests/:id", to: "friend_requests#accept"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :sender, class_name: :User, foreign_key: :sender_id
  belongs_to :receiver, class_name: :User, foreign_key: :receiver_id
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  before_action :set_friend_request, only: %i[ accept destroy ]
  before_action :authenticate_user!

  # GET /friend_requests or /friend_requests.json
  def index
    @incoming_requests = current_user.incoming_requests
    @outgoing_requests = current_user.outgoing_requests
  end

  # GET /friend_requests/new
  def new
    @friend_request = FriendRequest.new
  end

  # POST /friend_requests or /friend_requests.json
  def create
    @friend_request = FriendRequest.new(friend_request_params.merge(sender_id: current_user.id))

    respond_to do |format|
      if @friend_request.save
        format.html { redirect_to friend_requests_path, notice: "Friend request was successfully created." }
        format.json { render :show, status: :created, location: @friend_request }
      else
        p @friend_request.errors
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /friend_requests/1 or /friend_requests/1.json
  def accept
    if !@friend_request.nil? && @friend_request.receiver == current_user
      # create a friendship based on the friend request
      friendship=Friendship.new()
      friendship.primary_friend_id = @friend_request.sender_id
      friendship.secondary_friend_id = @friend_request.receiver_id
      if friendship.save
         @friend_request.destroy!
        respond_to do |format|
          format.html { redirect_to friend_requests_path, status: :see_other, notice: "Friend request accepted." }
          format.json { head :no_content }
        end
      end
     
    end
  end

  # DELETE /friend_requests/1 or /friend_requests/1.json
  def destroy
    if !@friend_request.nil?

      if @friend_request.sender == current_user
        @friend_request.destroy!
        respond_to do |format|
          format.html { redirect_to friend_requests_path, status: :see_other, notice: "Friend request cancelled." }
          format.json { head :no_content }
        end
      elsif @friend_request.receiver == current_user
        @friend_request.destroy!
        respond_to do |format|
          format.html { redirect_to friend_requests_path, status: :see_other, notice: "Friend request rejected." }
          format.json { head :no_content }
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend_request
      @friend_request = FriendRequest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_request_params
      params.require(:friend_request).permit(:receiver_id)
    end
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/views/friend_requests/_form.html.erb
<%= form_with(model: friend_request) do |form| %>
  <% if friend_request.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend_request.errors.count, "error") %> prohibited this friend_request from being saved:</h2>

      <ul>
        <% friend_request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :receiver_id, style: "display: block" %>
    <%= form.text_field :receiver_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/friend_requests/_friend_request.html.erb
<div id="<%= dom_id friend_request %>">

  <% if current_user==friend_request.sender %>
    <strong>Receiver:</strong>
    <%= friend_request.receiver.email %>
  <% elsif current_user==friend_request.receiver %>
    <strong>Sender:</strong>
    <%= friend_request.sender.email %>
  <% end %>

</div>

app/views/friend_requests/edit.html.erb
<% content_for :title, "Editing friend request" %>

<h1>Editing friend request</h1>

<%= render "form", friend_request: @friend_request %>

<br>

<div>
  <%= link_to "Show this friend request", @friend_request %> |
  <%= link_to "Back to friend requests", friend_requests_path %>
</div>

app/views/friend_requests/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Friend requests" %>

<h1>Friend requests</h1>

<h3>Incoming requests</h3>
<div id="incoming_requests">
  <% @incoming_requests.each do |friend_request| %>
      <%= render friend_request %>
      <%= button_to friend_request_path(friend_request), method: :post do %>
        Accept
      <% end %>
      <%= button_to friend_request_path(friend_request), method: :delete do %>
        Reject
      <% end %>
      <br>
      <br>
  <% end %>
</div>
<h3>Outgoing requests</h3>
<div id="outgoing_requests">
  <% @outgoing_requests.each do |friend_request| %>
    <%= render friend_request %>
    <%= button_to friend_request_path(friend_request), method: :delete do %>
      Cancel
    <% end %>
    <br>
    <br>
  <% end %>
</div>

<%= link_to "New friend request", new_friend_request_path %>

app/views/friend_requests/new.html.erb
<% content_for :title, "New friend request" %>

<h1>New friend request</h1>

<%= render "form", friend_request: @friend_request %>

<br>

<div>
  <%= link_to "Back to friend requests", friend_requests_path %>
</div>

app/views/friend_requests/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @friend_request %>

<div>
  <%= link_to "Edit this friend request", edit_friend_request_path(@friend_request) %> |
  <%= link_to "Back to friend requests", friend_requests_path %>

  <%= button_to "Destroy this friend request", @friend_request, method: :delete %>
</div>