config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :friendships, only: [ :index, :destroy ]
  resources :friend_requests, only: [ :index, :new, :create, :destroy ]
  post "/friend_requests/:id", to: "friend_requests#accept"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Friend Request App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
  <% if user_signed_in? %>
      <p> Your User ID: <%= current_user.id %></p>
      <%= button_to destroy_user_session_path, method: :delete do %>
      Log Out
      <% end %>
      <%= link_to "Friend Requests", friend_requests_path%>
      <br>
      <%= link_to "Friendships", friendships_path%>
  <% else %>
      <%= button_to new_user_registration_path, method: :get do %>
      Sign Up
      <% end %>
      <%= button_to new_user_session_path, method: :get do %>
      Log In
      <% end %>
  <% end %>

    <%= yield %>
  </body>
</html>